---
deployment:
  tasks:
        - export DEPLOYPATH=/home/danyialshahid/bin/.test/ITworld.com.pk/affiliateplatform/application/
        - /bin/cp index.html $DEPLOYPATH 
        #- /bin/cp * $DEPLOYPATH #copy all from root
        #- /bin/cp <file_name> $DEPLOYPATH #Copy specific file to destination from root
        #- /bin/cp /<sub_folder>/<file_name> $DEPLOYPATH #copy specific file from source sub folder
        #- /bin cp /<sub_folder>/* $DEPLOYPATH #copy all from sub folder root  