<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Categories_model extends MY_Model{
	 
	
	public $return_response = array(
		
		'ERROR'			=> FALSE,
		'MESSAGE'		=> '',
		'DATA'			=> array()
	
	);
	

	public function get_all($where=null){
   
		$this->db->order_by('id','desc');
		if($where){ $this->db->where($where);	 }	   
			$data = $this->db->get_where('categories',[
					'site_id'=>$this->session->userdata('user_active_site')
			])->result();
		
		return $data;


	}

 	public function get_all_groups($where=null){
   
		$this->db->order_by('id','desc');
		if($where){ $this->db->where($where);	 }	   
			$data = $this->db->get_where('categories_group',[
					'site_id'=>$this->session->userdata('user_active_site')
			])->result();
		
		return $data;


	}

 
	public function add($uploaded_filename,$update=false,$id=null){
		// d($this->input->post());
		$data=array( 
			'name'		=> $this->input->post('name'),
			'slug'		=> $this->input->post('slug'), 
			'added_date'	=> date('y-m-d h:i:s'),
			'updated_date'		=> date('y-m-d h:i:s'),
			'description'		=> $this->input->post('description'),
			'status'		=> $this->input->post('status'),
			'inserted_from'		=>'human',  
			'popular'		=>$this->input->post('check_popular'), 
			'show_in_home'		=>$this->input->post('check_show_in_home'), 
			'top'		=>$this->input->post('check_top'), 
			'icon'		=>$this->input->post('icon'), 
			'site_id'		=>$this->session->userdata('user_active_site'), 
			'categories_group_id'		=>$this->input->post('categories_group_id'), 
			'seo_category_meta_title'		=>$this->input->post('seo_category_meta_title'), 
			'seo_category_meta_keywords'		=>$this->input->post('seo_category_meta_keywords'), 
			'seo_category_meta_description'		=>$this->input->post('seo_category_meta_description'),  
		
		);
		if(!empty($uploaded_filename)){
			$data['feature_image']=	$uploaded_filename;
		}

		if($update && $id!=null){
								$this->db->where('id' ,$id );
					$update=$this->db->update('categories' ,$data );
						return $update;

		}else{
				$insert=$this->db->insert('categories' ,$data );
		 
				return $insert;
			}
	}

	 
	public function add_group($uploaded_filename,$update=false,$id=null){
		// d($this->input->post());
		$data=array( 
			'name'		=> $this->input->post('name'),
			'slug'		=> $this->input->post('slug'), 
			'added_date'	=> date('y-m-d h:i:s'),
			'updated_date'		=> date('y-m-d h:i:s'),
			'description'		=> $this->input->post('description'),
			'status'		=> $this->input->post('status'),
			'inserted_from'		=>'human',  
			 
			'icon'		=>$this->input->post('icon'), 
			'site_id'		=>$this->session->userdata('user_active_site'), 
			'seo_category_group_meta_title'		=>$this->input->post('seo_category_group_meta_title'), 
			'seo_category_group_meta_keywords'		=>$this->input->post('seo_category_group_meta_keywords'), 
			'seo_category_group_meta_description'		=>$this->input->post('seo_category_group_meta_description'),  
		
		);
		if(!empty($uploaded_filename)){
			$data['feature_image']=	$uploaded_filename;
		}

		if($update && $id!=null){
								$this->db->where('id' ,$id );
					$update=$this->db->update('categories_group' ,$data );
						return $update;

		}else{
				$insert=$this->db->insert('categories_group' ,$data );
		 
				return $insert;
			}
	}

	


	public function delete($id){
		
		
		 
		$this->db->where('id' , $id);
		if($this->db->delete('categories' )){
			return true;
		}else{

			return ['error'=>''];
			 }
		  
	}	

	public function delete_group($id){
		
		
		 
		$this->db->where('id' , $id);
		if($this->db->delete('categories_group' )){
			return true;
		}else{

			return ['error'=>''];
			 }
		  
	}


	public function paste($items){
		$rows=[];

		foreach ($items as $item) {
				$row=$item['row'];
				$row->site_id= $this->session->userdata('user_active_site');
				$row->inserted_from='paste';
				unset($row->id); 
				$rows[]=(array)$row;

		 	
		}
	 

 $complete=$this->db->insert_batch('categories',$rows); 
		if ($complete) {
		    return true;
		 }	 else{
		 	return false;
		 }
	

	}
	
 public function $this->rand1(){

	return random_int(0,1);
}

	public function add_dummy_categories($site_id){
$this->db->set('categories_group_id',null)->where('site_id',$site_id)->update('categories'); 
 $this->db->where('site_id',$site_id)->delete('categories_group');  
 $categories_groups=[
	['name'=>'Fashion',
	'slug'=>'fashion',
	'number'=>1,
	'description'=>'',
	'feature_image'=>'fashion.png',
	'icon'=>'pencil-ruler',
	],
	['name'=>'Business & Office Supplies',
	'slug'=>'business_office_supplies',
	'number'=>2,
	'description'=>'',
	'feature_image'=>'business_office_supplies.png',
	'icon'=>'pencil-ruler',
	],
	['name'=>'Finance',
	'slug'=>'finance',
	'number'=>3,
	'description'=>'',
	'feature_image'=>'finance.png',
	'icon'=>'pencil-ruler',
	],
	['name'=>'Special Occasions',
	'slug'=>'special_occasions',
	'number'=>4,
	'description'=>'',
	'feature_image'=>'special_occasions.png',
	'icon'=>'pencil-ruler',
	],
	['name'=>'Health & Beauty',
	'slug'=>'health_and_beauty',
	'number'=>5,
	'description'=>'',
	'feature_image'=>'health_and_beauty.png',
	'icon'=>'pencil-ruler',
	],
	['name'=>'Children & Babies',
	'slug'=>'children_and_babies',
	'number'=>6,
	'description'=>'',
	'feature_image'=>'children_and_babies.png',
	'icon'=>'pencil-ruler',
	],
	['name'=>'Food & Drink',
	'slug'=>'food_and_drink',
	'number'=>7,
	'description'=>'',
	'feature_image'=>'food_and_drink.png',
	'icon'=>'pencil-ruler',
	],
	['name'=>'Travel',
	'slug'=>'travel',
	'number'=>8,
	'description'=>'',
	'feature_image'=>'travel.png',
	'icon'=>'pencil-ruler',
	],
	['name'=>'Days Out & Experiences',
	'slug'=>'days_out_and_experiences',
	'number'=>9,
	'description'=>'',
	'feature_image'=>'days_out_and_experiences.png',
	'icon'=>'pencil-ruler',
	],
	['name'=>'Gifts & Flowers',
	'slug'=>'gifts_and_flowers',
	'number'=>10,
	'description'=>'',
	'feature_image'=>'gifts_and_flowers.png',
	'icon'=>'pencil-ruler',
	],
	['name'=>'Sports & Outdoors',
	'slug'=>'sports_and_outdoors',
	'number'=>11,
	'description'=>'',
	'feature_image'=>'sports_and_outdoors.png',
	'icon'=>'pencil-ruler',
	],
	['name'=>'Department Stores',
	'slug'=>'department_stores',
	'number'=>12,
	'description'=>'',
	'feature_image'=>'department_stores.png',
	'icon'=>'pencil-ruler',
	],
	['name'=>'Home & Garden',
	'slug'=>'home_and_garden',
	'number'=>13,
	'description'=>'',
	'feature_image'=>'home_and_garden.png',
	'icon'=>'pencil-ruler',
	],
	['name'=>'Students Discount',
	'slug'=>'student_discount',
	'number'=>14,
	'description'=>'',
	'feature_image'=>'student_discount.png',
	'icon'=>'pencil-ruler',
	],
	['name'=>'Animals & Pets',
	'slug'=>'animals_and_pets',
	'number'=>15,
	'description'=>'',
	'feature_image'=>'animals_and_pets.png',
	'icon'=>'pencil-ruler',
	],
	['name'=>'Education & Training',
	'slug'=>'education_and_training',
	'number'=>16,
	'description'=>'',
	'feature_image'=>'education_and_training.png',
	'icon'=>'pencil-ruler',
	],
	['name'=>'Technology',
	'slug'=>'technology',
	'number'=>17,
	'description'=>'',
	'feature_image'=>'technology.png',
	'icon'=>'pencil-ruler',
	],
	['name'=>'Automotive',
	'slug'=>'automotive',
	'number'=>18,
	'description'=>'',
	'feature_image'=>'automotive.png',
	'icon'=>'pencil-ruler',
	],
	['name'=>'Entertainment',
	'slug'=>'entertainment',
	'number'=>19,
	'description'=>'',
	'feature_image'=>'entertainment.png',
	'icon'=>'pencil-ruler',
	], 
	['name'=>'Sustainable Living',
	'slug'=>'sustainable_living',
	'number'=>20,
	'description'=>'',
	'feature_image'=>'sustainable_living.png',
	'icon'=>'pencil-ruler',
	], 
	['name'=>'Mix & Etc',
	'slug'=>'others',
	'number'=>22,
	'description'=>'',
	'feature_image'=>'others.png',
	'icon'=>'pencil-ruler',
	], 
];
foreach ($categories_groups as  &$category_group) {
	$number=$category_group['number'];
	$category_group['site_id']=$site_id;
	$category_group['status']='active';
	unset($category_group['number']);
	$this->db->insert('categories_group',$category_group); 
	$id=$this->db->insert_id();
	$category_group['number']=$number;
	$category_group['id']=$id; 
}


$this->db->set('category_id',null)->where('site_id',$site_id)->update('stores'); 
$this->db->set('category_id',null)->where('site_id',$site_id)->update('coupons'); 
$this->db->where('site_id',$site_id)->delete('categories'); 
$categories=[

	[
	'name'=>'Accessories',
	'slug'=>'accessories',
	'feature_image'=>'accessories.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>1,
	],
	[
	'name'=>'Accessories',
	'slug'=>'accessories',
	'feature_image'=>'accessories.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>1,
	],
	[
	'name'=>'Childrens Fashion',
	'slug'=>'childrens_fashion',
	'feature_image'=>'childrens_fashion.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>1,
	],
	[
	'name'=>'Jewellery & Watches',
	'slug'=>'jewellery_and_watches',
	'feature_image'=>'jewellery_and_watches.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>1,
	],
	[
	'name'=>'Lingerie',
	'slug'=>'lingerie',
	'feature_image'=>'lingerie.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>1,
	],
	[
	'name'=>'Mens Fashion',
	'slug'=>'mens_fashion',
	'feature_image'=>'mens_fashion.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>1,
	],
	[
	'name'=>'Shoes',
	'slug'=>'shoes',
	'feature_image'=>'shoes.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>1,
	],
	[
	'name'=>'Womens Fashion',
	'slug'=>'womens_fashion',
	'feature_image'=>'womens_fashion.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>1,
	],
	[
	'name'=>'Courier',
	'slug'=>'courier',
	'feature_image'=>'courier.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>2,
	],
	[
	'name'=>'Ink and Toners',
	'slug'=>'ink_and_toners',
	'feature_image'=>'ink_and_toners.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>2,
	],
	[
	'name'=>'Office Supplies',
	'slug'=>'office_supplies',
	'feature_image'=>'office_supplies.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>2,
	],
	[
	'name'=>'Web Hosting',
	'slug'=>'web_hosting',
	'feature_image'=>'web_hosting.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>2,
	],
	[
	'name'=>'Insurance Services',
	'slug'=>'insurance_services',
	'feature_image'=>'insurance_services.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>3,
	],
	[
	'name'=>'Money Transfers',
	'slug'=>'money_transfers',
	'feature_image'=>'money_transfers.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>3,
	],
	[
	'name'=>'Utilities',
	'slug'=>'utilities',
	'feature_image'=>'utilities.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>3,
	],
	[
	'name'=>'Fashion Week',
	'slug'=>'fashion_week',
	'feature_image'=>'fashion_week.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>4,
	],
	[
	'name'=>'Black Friday',
	'slug'=>'black_friday',
	'feature_image'=>'black_friday.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>4,
	],
	[
	'name'=>'Christmas and New Year',
	'slug'=>'christmas_and_new_year',
	'feature_image'=>'christmas_and_new_year.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>4,
	],
	[
	'name'=>'Cyber Monday',
	'slug'=>'cyber_monday',
	'feature_image'=>'cyber_monday.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>4,
	],
	[
	'name'=>'Easter',
	'slug'=>'easter',
	'feature_image'=>'easter.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>4,
	],
	[
	'name'=>'Father\'s Day',
	'slug'=>'father\'s_day',
	'feature_image'=>'father\'s_day.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>4,
	],
	[
	'name'=>'Giving Tuesday',
	'slug'=>'giving_tuesday',
	'feature_image'=>'giving_tuesday.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>4,
	],
	[
	'name'=>'Halloween',
	'slug'=>'halloween',
	'feature_image'=>'halloween.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>4,
	],
	[
	'name'=>'Mother\'s Day',
	'slug'=>'mother\'s_day',
	'feature_image'=>'mother\'s_day.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>4,
	],
	[
	'name'=>'Singles Day',
	'slug'=>'singles_day',
	'feature_image'=>'singles_day.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>4,
	],
	[
	'name'=>'Valentine\'s Day',
	'slug'=>'valentine\'s_day',
	'feature_image'=>'valentine\'s_day.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>4,
	],
	[
	'name'=>'Weddings and Engagements',
	'slug'=>'weddings_and_engagements',
	'feature_image'=>'weddings_and_engagements.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>4,
	],
	[
	'name'=>'Beauty & Skin Care',
	'slug'=>'beauty_and_skin_care',
	'feature_image'=>'beauty_and_skin_care.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>5,
	],
	[
	'name'=>'Contact Lenses and Eye Care',
	'slug'=>'contact_lenses_and_eye_care',
	'feature_image'=>'contact_lenses_and_eye_care.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>5,
	],
	[
	'name'=>'Diet & Nutrition',
	'slug'=>'diet_and_nutrition',
	'feature_image'=>'diet_and_nutrition.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>5,
	],
	[
	'name'=>'Fragrances',
	'slug'=>'fragrances',
	'feature_image'=>'fragrances.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>5,
	],
	[
	'name'=>'Hair Care',
	'slug'=>'hair_care',
	'feature_image'=>'hair_care.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>5,
	],
	[
	'name'=>'Pharmacy',
	'slug'=>'pharmacy',
	'feature_image'=>'pharmacy.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>5,
	],
	[
	'name'=>'Baby Clothing',
	'slug'=>'baby_clothing',
	'feature_image'=>'baby_clothing.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>6,
	],
	[
	'name'=>'Car Seats & Prams',
	'slug'=>'car_seats_and_prams',
	'feature_image'=>'car_seats_and_prams.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>6,
	],
	[
	'name'=>'Feeding and Accessories',
	'slug'=>'feeding_and_accessories',
	'feature_image'=>'feeding_and_accessories.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>6,
	],
	[
	'name'=>'Maternity',
	'slug'=>'maternity',
	'feature_image'=>'maternity.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>6,
	],
	[
	'name'=>'Nursery',
	'slug'=>'nursery',
	'feature_image'=>'nursery.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>6,
	],
	[
	'name'=>'Toys & Fun',
	'slug'=>'toys_and_fun',
	'feature_image'=>'toys_and_fun.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>6,
	],
	[
	'name'=>'Groceries',
	'slug'=>'groceries',
	'feature_image'=>'groceries.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>7,
	],
	[
	'name'=>'Restaurants',
	'slug'=>'restaurants',
	'feature_image'=>'restaurants.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>7,
	],
	[
	'name'=>'Takeaway & Delivery',
	'slug'=>'takeaway_and_delivery',
	'feature_image'=>'takeaway_and_delivery.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>7,
	],
	[
	'name'=>'Coaches & Trains',
	'slug'=>'coaches_and_trains',
	'feature_image'=>'coaches_and_trains.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>8,
	],
	[
	'name'=>'Coaches & Trains',
	'slug'=>'coaches_and_trains',
	'feature_image'=>'coaches_and_trains.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>8,
	],
	[
	'name'=>'Flights',
	'slug'=>'flights',
	'feature_image'=>'flights.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>8,
	],
	[
	'name'=>'Holidays',
	'slug'=>'holidays',
	'feature_image'=>'holidays.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>8,
	],
	[
	'name'=>'Hotels & Accommodation',
	'slug'=>'hotels_and_accommodation',
	'feature_image'=>'hotels_and_accommodation.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>8,
	],
	[
	'name'=>'Luggage and Accessories',
	'slug'=>'luggage_and_accessories',
	'feature_image'=>'luggage_and_accessories.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>8,
	],
	[
	'name'=>'Parking & Transfers',
	'slug'=>'parking_and_transfers',
	'feature_image'=>'parking_and_transfers.png',
	'description'=>'', 
	'slug'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>8,
	],
	[
	'name'=>'Travel Insurance',
	'slug'=>'travel_insurance',
	'feature_image'=>'travel_insurance.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>8,
	],
	[
	'name'=>'Dating and Social',
	'slug'=>'dating_and_social',
	'feature_image'=>'dating_and_social.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>9,
	],
	[
	'name'=>'Events and Cinema',
	'slug'=>'events_and_cinema',
	'feature_image'=>'events_and_cinema.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>9,
	],
	[
	'name'=>'Experience Days',
	'slug'=>'experience_days',
	'feature_image'=>'experience_days.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>9,
	],
	[
	'name'=>'Theatre',
	'slug'=>'theatre',
	'feature_image'=>'theatre.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>9,
	],
	[
	'name'=>'Adult',
	'slug'=>'adult',
	'feature_image'=>'adult.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>10,
	],
	[
	'name'=>'Confectionery',
	'slug'=>'confectionery',
	'feature_image'=>'confectionery.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>10,
	],
	[
	'name'=>'Flowers',
	'slug'=>'flowers',
	'feature_image'=>'flowers.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>10,
	],
	[
	'name'=>'Gift Experiences',
	'slug'=>'gift_experiences',
	'feature_image'=>'gift_experiences.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>10,
	],
	[
	'name'=>'Gifts for Her',
	'slug'=>'gifts_for_her',
	'feature_image'=>'gifts_for_her.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>10,
	],
	[
	'name'=>'Gifts for Him',
	'slug'=>'gifts_for_him',
	'feature_image'=>'gifts_for_him.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>10,
	],
	[
	'name'=>'Greetings Cards',
	'slug'=>'greetings_cards',
	'feature_image'=>'greetings_cards.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>10,
	],
	[
	'name'=>'Outdoors',
	'slug'=>'outdoors',
	'feature_image'=>'outdoors.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>11,
	],
	[
	'name'=>'Sports Clothing',
	'slug'=>'sports_clothing',
	'feature_image'=>'sports_clothing.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>11,
	],
	[
	'name'=>'Sports Equipment',
	'slug'=>'sports_equipment',
	'feature_image'=>'sports_equipment.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>11,
	],
	[
	'name'=>'Sports Equipment',
	'slug'=>'sports_equipment',
	'feature_image'=>'sports_equipment.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>11,
	],
	[
	'name'=>'Art & Posters',
	'slug'=>'art_and_posters',
	'feature_image'=>'art_and_posters.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>13,
	],
	[
	'name'=>'Art & Posters',
	'slug'=>'art_and_posters',
	'feature_image'=>'art_and_posters.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>13,
	],
	[
	'name'=>'Bedroom',
	'slug'=>'bedroom',
	'feature_image'=>'bedroom.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>13,
	],
	[
	'name'=>'Bedroom',
	'slug'=>'bedroom',
	'feature_image'=>'bedroom.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>13,
	],
	[
	'name'=>'DIY',
	'slug'=>'diy',
	'feature_image'=>'diy.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>13,
	],
	[
	'name'=>'Furnishing',
	'slug'=>'furnishing',
	'feature_image'=>'furnishing.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>13,
	],
	[
	'name'=>'Garden',
	'slug'=>'garden',
	'feature_image'=>'garden.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>13,
	],
	[
	'name'=>'Household Appliances',
	'slug'=>'household_appliances',
	'feature_image'=>'household_appliances.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>13,
	],
	[
	'name'=>'Kitchen',
	'slug'=>'kitchen',
	'feature_image'=>'kitchen.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>13,
	],
	[
	'name'=>'Lighting',
	'slug'=>'lighting',
	'feature_image'=>'lighting.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>13,
	],
	[
	'name'=>'Back to School',
	'slug'=>'back_to_school',
	'feature_image'=>'back_to_school.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>16,
	],
	[
	'name'=>'Online Learning',
	'slug'=>'online_learning',
	'feature_image'=>'online_learning.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>16,
	],
	[
	'name'=>'Computer Accessories',
	'slug'=>'computer_accessories',
	'feature_image'=>'computer_accessories.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>17,
	],
	[
	'name'=>'Computers & Laptops',
	'slug'=>'computers_and_laptops',
	'feature_image'=>'computers_and_laptops.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>17,
	],
	[
	'name'=>'Phones & Tablets',
	'slug'=>'phones_and_tablets',
	'feature_image'=>'phones_and_tablets.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>17,
	],
	[
	'name'=>'Photography & Prints',
	'slug'=>'photography_and_prints',
	'feature_image'=>'photography_and_prints.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>17,
	],
	[
	'name'=>'Printers',
	'slug'=>'printers',
	'feature_image'=>'printers.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>17,
	],
	[
	'name'=>'Software',
	'slug'=>'software',
	'feature_image'=>'software.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>17,
	],
	[
	'name'=>'Sound & Vision',
	'slug'=>'sound_and_vision',
	'feature_image'=>'sound_and_vision.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>17,
	],
	[
	'name'=>'Streaming & Satellite Providers',
	'slug'=>'streaming_and_satellite_providers',
	'feature_image'=>'streaming_and_satellite_providers.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>17,
	],
	[
	'name'=>'Car Accessories',
	'slug'=>'car_accessories',
	'feature_image'=>'car_accessories.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>18,
	],
	[
	'name'=>'Car and Vehicle Hire',
	'slug'=>'car_and_vehicle_hire',
	'feature_image'=>'car_and_vehicle_hire.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>18,
	],
	[
	'name'=>'MOT & Servicing',
	'slug'=>'mot_and_servicing',
	'feature_image'=>'mot_and_servicing.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>18,
	],
	[
	'name'=>'Sat Navs',
	'slug'=>'sat_navs',
	'feature_image'=>'sat_navs.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>18,
	],
	[
	'name'=>'Tyres',
	'slug'=>'tyres',
	'feature_image'=>'tyres.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>18,
	],
	[
	'name'=>'Tyres',
	'slug'=>'tyres',
	'feature_image'=>'tyres.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>18,
	],
	[
	'name'=>'Books',
	'slug'=>'books',
	'feature_image'=>'books.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>19,
	],
	[
	'name'=>'Film & TV',
	'slug'=>'film_and_tv',
	'feature_image'=>'film_and_tv.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>19,
	],
	[
	'name'=>'Games',
	'slug'=>'games',
	'feature_image'=>'games.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>19,
	],
	[
	'name'=>'Hobbies',
	'slug'=>'hobbies',
	'feature_image'=>'hobbies.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>19,
	],
	[
	'name'=>'Magazines & Subscriptions',
	'slug'=>'magazines_and_subscriptions',
	'feature_image'=>'magazines_and_subscriptions.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>19,
	],
	[
	'name'=>'Insurance Services',
	'slug'=>'insurance_services',
	'feature_image'=>'insurance_services.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	],
	[
	'name'=>'Beauty',
	'slug'=>'beauty',
	'feature_image'=>'beauty.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	],
	[
	'name'=>'Books',
	'slug'=>'books',
	'feature_image'=>'books.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	],
	[
	'name'=>'Clothing',
	'slug'=>'clothing',
	'feature_image'=>'clothing.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	],
	[
	'name'=>'Electronics',
	'slug'=>'electronics',
	'feature_image'=>'electronics.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	],
	[
	'name'=>'Entertainment',
	'slug'=>'entertainment',
	'feature_image'=>'entertainment.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	],
	[
	'name'=>'Flowers',
	'slug'=>'flowers',
	'feature_image'=>'flowers.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	],
	[
	'name'=>'Food & Dining',
	'slug'=>'food_and_dining',
	'feature_image'=>'food_and_dining.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	],
	[
	'name'=>'Gifts',
	'slug'=>'gifts',
	'feature_image'=>'gifts.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	],
	[
	'name'=>'Pets',
	'slug'=>'pets',
	'feature_image'=>'pets.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	],
	[
	'name'=>'Photos',
	'slug'=>'photos',
	'feature_image'=>'photos.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	],
	[
	'name'=>'Shoes',
	'slug'=>'shoes',
	'feature_image'=>'shoes.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	],
	[
	'name'=>'Small Appliances',
	'slug'=>'small_appliances',
	'feature_image'=>'small_appliances.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	],
	[
	'name'=>'Sports',
	'slug'=>'sports',
	'feature_image'=>'sports.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	],
	[
	'name'=>'Toys',
	'slug'=>'toys',
	'feature_image'=>'toys.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	],
	[
	'name'=>'Travel',
	'slug'=>'travel',
	'feature_image'=>'travel.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	],
	[
	'name'=>'ac',
	'slug'=>'ac',
	'feature_image'=>'ac.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'all fashion',
	'slug'=>'all_fashion',
	'feature_image'=>'all_fashion.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'amusement and water parks',
	'slug'=>'amusement_and_water_parks',
	'feature_image'=>'amusement_and_water_parks.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'baby care',
	'slug'=>'baby_care',
	'feature_image'=>'baby_care.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'bed & bath',
	'slug'=>'bed_and_bath',
	'feature_image'=>'bed_and_bath.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'bill payment',
	'slug'=>'bill_payment',
	'feature_image'=>'bill_payment.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'blank',
	'slug'=>'blank',
	'feature_image'=>'blank.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'broadband bill',
	'slug'=>'broadband_bill',
	'feature_image'=>'broadband_bill.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'bus ticket',
	'slug'=>'bus_ticket',
	'feature_image'=>'bus_ticket.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'buy 1 get 1free.png',
	'slug'=>'buy_1_get_1free.png',
	'feature_image'=>'buy_1_get_1free.png.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'camera & accessories',
	'slug'=>'camera_and_accessories',
	'feature_image'=>'camera_and_accessories.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'car & motorbikes',
	'slug'=>'car_and_motorbikes',
	'feature_image'=>'car_and_motorbikes.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'car rental',
	'slug'=>'car_rental',
	'feature_image'=>'car_rental.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'confectionery',
	'slug'=>'confectionery',
	'feature_image'=>'confectionery.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'customize',
	'slug'=>'customize',
	'feature_image'=>'customize.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'data card',
	'slug'=>'data_card',
	'feature_image'=>'data_card.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'desktop & laptops',
	'slug'=>'desktop_and_laptops',
	'feature_image'=>'desktop_and_laptops.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'diapers',
	'slug'=>'diapers',
	'feature_image'=>'diapers.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'doctor appointment',
	'slug'=>'doctor_appointment',
	'feature_image'=>'doctor_appointment.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'domains',
	'slug'=>'domains',
	'feature_image'=>'domains.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'domestic air ticket',
	'slug'=>'domestic_air_ticket',
	'feature_image'=>'domestic_air_ticket.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'drinks & beverages',
	'slug'=>'drinks_and_beverages',
	'feature_image'=>'drinks_and_beverages.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'dth',
	'slug'=>'dth',
	'feature_image'=>'dth.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'ebooks',
	'slug'=>'ebooks',
	'feature_image'=>'ebooks.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'editors pick',
	'slug'=>'editors_pick',
	'feature_image'=>'editors_pick.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'electricity bill',
	'slug'=>'electricity_bill',
	'feature_image'=>'electricity_bill.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'events & concerts',
	'slug'=>'events_and_concerts',
	'feature_image'=>'events_and_concerts.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'exchange offer',
	'slug'=>'exchange_offer',
	'feature_image'=>'exchange_offer.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'footwear',
	'slug'=>'footwear',
	'feature_image'=>'footwear.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'freecharge wallet offers',
	'slug'=>'freecharge_wallet_offers',
	'feature_image'=>'freecharge_wallet_offers.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'furniture',
	'slug'=>'furniture',
	'feature_image'=>'furniture.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'gas bill',
	'slug'=>'gas_bill',
	'feature_image'=>'gas_bill.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'gift cards',
	'slug'=>'gift_cards',
	'feature_image'=>'gift_cards.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'gold & silver coins',
	'slug'=>'gold_and_silver_coins',
	'feature_image'=>'gold_and_silver_coins.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'grocery',
	'slug'=>'grocery',
	'feature_image'=>'grocery.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'headphones & speakers',
	'slug'=>'headphones_and_speakers',
	'feature_image'=>'headphones_and_speakers.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'health and beauty',
	'slug'=>'health_and_beauty',
	'feature_image'=>'health_and_beauty.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'health devices',
	'slug'=>'health_devices',
	'feature_image'=>'health_devices.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'health supplements',
	'slug'=>'health_supplements',
	'feature_image'=>'health_supplements.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'holiday package',
	'slug'=>'holiday_package',
	'feature_image'=>'holiday_package.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'home decor',
	'slug'=>'home_decor',
	'feature_image'=>'home_decor.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'home furnishing',
	'slug'=>'home_furnishing',
	'feature_image'=>'home_furnishing.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'home services',
	'slug'=>'home_services',
	'feature_image'=>'home_services.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'hotels',
	'slug'=>'hotels',
	'feature_image'=>'hotels.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 		
	[
	'name'=>'international air ticket',
	'slug'=>'international_air_ticket',
	'feature_image'=>'international_air_ticket.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'jewellery & accessories',
	'slug'=>'jewellery_and_accessories',
	'feature_image'=>'jewellery_and_accessories.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'kids clothing',
	'slug'=>'kids_clothing',
	'feature_image'=>'kids_clothing.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'kids footwear',
	'slug'=>'kids_footwear',
	'feature_image'=>'kids_footwear.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'kitchen & dining',
	'slug'=>'kitchen_and_dining',
	'feature_image'=>'kitchen_and_dining.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'landline bill',
	'slug'=>'landline_bill',
	'feature_image'=>'landline_bill.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'lighting',
	'slug'=>'lighting',
	'feature_image'=>'lighting.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'local services',
	'slug'=>'local_services',
	'feature_image'=>'local_services.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'magazines',
	'slug'=>'magazines',
	'feature_image'=>'magazines.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'media, gaming & software',
	'slug'=>'media,_gaming_and_software',
	'feature_image'=>'media,_gaming_and_software.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'medicine',
	'slug'=>'medicine',
	'feature_image'=>'medicine.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'metro card',
	'slug'=>'metro_card',
	'feature_image'=>'metro_card.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'mixer juicer grinders',
	'slug'=>'mixer_juicer_grinders',
	'feature_image'=>'mixer_juicer_grinders.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'mobikwik wallet offers',
	'slug'=>'mobikwik_wallet_offers',
	'feature_image'=>'mobikwik_wallet_offers.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'mobile & tablet cases and covers',
	'slug'=>'mobile_and_tablet_cases_and_covers',
	'feature_image'=>'mobile_and_tablet_cases_and_covers.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'mobile recharge',
	'slug'=>'mobile_recharge',
	'feature_image'=>'mobile_recharge.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'mobiles',
	'slug'=>'mobiles',
	'feature_image'=>'mobiles.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'movie ticket offers',
	'slug'=>'movie_ticket_offers',
	'feature_image'=>'movie_ticket_offers.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'new year offers',
	'slug'=>'new_year_offers',
	'feature_image'=>'new_year_offers.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'others',
	'slug'=>'others',
	'feature_image'=>'others.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'perfumes & deos',
	'slug'=>'perfumes_and_deos',
	'feature_image'=>'perfumes_and_deos.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'personal and healthcare ',
	'slug'=>'personal_and_healthcare_',
	'feature_image'=>'personal_and_healthcare_.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'pizza',
	'slug'=>'pizza',
	'feature_image'=>'pizza.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'postpaid mobile bill',
	'slug'=>'postpaid_mobile_bill',
	'feature_image'=>'postpaid_mobile_bill.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'recharge',
	'slug'=>'recharge',
	'feature_image'=>'recharge.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'refrigerators',
	'slug'=>'refrigerators',
	'feature_image'=>'refrigerators.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'restaurants offers',
	'slug'=>'restaurants_offers',
	'feature_image'=>'restaurants_offers.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'school supplies',
	'slug'=>'school_supplies',
	'feature_image'=>'school_supplies.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'sports and fitness equipments',
	'slug'=>'sports_and_fitness_equipments',
	'feature_image'=>'sports_and_fitness_equipments.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'staionary',
	'slug'=>'staionary',
	'feature_image'=>'staionary.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'stationery & office supplies',
	'slug'=>'stationery_and_office_supplies',
	'feature_image'=>'stationery_and_office_supplies.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'storage devices',
	'slug'=>'storage_devices',
	'feature_image'=>'storage_devices.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'study material & online courses',
	'slug'=>'study_material_and_online_courses',
	'feature_image'=>'study_material_and_online_courses.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'sunglasses',
	'slug'=>'sunglasses',
	'feature_image'=>'sunglasses.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'televisions',
	'slug'=>'televisions',
	'feature_image'=>'televisions.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'tools & hardware',
	'slug'=>'tools_and_hardware',
	'feature_image'=>'tools_and_hardware.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'train ticket',
	'slug'=>'train_ticket',
	'feature_image'=>'train_ticket.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'velintine',
	'slug'=>'velintine',
	'feature_image'=>'velintine.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'wallet offers',
	'slug'=>'wallet_offers',
	'feature_image'=>'wallet_offers.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'washing machine',
	'slug'=>'washing_machine',
	'feature_image'=>'washing_machine.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'watches',
	'slug'=>'watches',
	'feature_image'=>'watches.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	], 	
	[
	'name'=>'water bill',
	'slug'=>'water_bill',
	'feature_image'=>'water_bill.png',
	'description'=>'',
	'icon'=>'pencil-ruler',
	'popular'=>$this->rand1(),
	'show_in_home'=>$this->rand1(),
	'top'=>$this->rand1(),
	'group'=>22,
	]
];

foreach ($categories as  &$category) {
	$group=$category['group'];
	unset($category['group']);
	$categories_group_id=null;
	foreach ($categories_groups as  $category_group) {
		if ($group==$category_group['number']) {
			$categories_group_id=$category_group['id'];
		}
	}

	$category['site_id']=$site_id;
	$category['categories_group_id']=$categories_group_id;
	$category['status']='active';

}
$this->db->insert_batch('categories',$categories); 
 
return true;


	

	}
	
 

	
}